### register
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "test@mail.ru",
  "password": "awdawdawdawdawd_awdawd_awd"
}

### login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "test@mail.ru",
  "password": "awdawdawdawdawd_awdawd_awd"
}

### logout
POST {{host}}/auth/logout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYTM2MzcyZi1mOTMxLTQ1MGItOTMxYy02ZWQyNDFhNTA5NDYiLCJpYXQiOjE2NTgzODc2MzUsImV4cCI6MTY2MDk3OTYzNX0.YOZsOGQrSjqUhK5tIp4X2d0mMIQ-o29atXmnpjAHV8A

### refresh
POST {{host}}/auth/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZDc3MTVjNS01NjUzLTQ3MzQtYjk2Yi0zYTRhYmFlYTQ3OTAiLCJpYXQiOjE2NTg0MDIzMDUsImV4cCI6MTY2MDk5NDMwNX0.nEYjTKvQEsd2jtzl08hMOv0OAbXc5-gRX6hjS-uMzto
