### getUserProfile
GET {{host}}/user
Authorization: Bearer {{accessToken}}

### updateUserProfile
PATCH {{host}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "{{userId}}",
  "email": "{{email}}",
  "isActive": true,
  "firstName": "art",
  "lastName": "art",
  "nickname": "123",
  "bio": "awd"
}
