### getUserProfile
GET {{host}}/user
Cookie: accessToken={{accessToken}}

### updateUserProfile
PATCH {{host}}/user
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "userId": "{{userId}}",
  "email": "{{email}}",
  "isActive": true,
  "firstName": "art",
  "lastName": "art",
  "nickname": "123",
  "bio": "awd"
}
