### createGift
POST {{host}}/gifts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "text": "333333",
  "title": "333333333",
  "userId": "{{userId}}"
}

### updateGift
PATCH {{host}}/gifts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "giftId": "c6073c26-6871-4221-8a20-6cd7d297910f",
  "text": "123",
  "title": "aw123d",
  "userId": "{{userId}}"
}

### getGift
GET {{host}}/gifts?userId={{userId}}&skip=2
Authorization: Bearer {{accessToken}}
