---
version: '3.8'
services:
  rmq:
    container_name: rmq
    image: rabbitmq:3-management
    volumes:
      - ${DOCKER_VOLUMES}/rmq:/data/postgres
    ports:
      - '15672:15672'
      - '5672:5672'

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      PGDATA: /data/postgres
    volumes:
      - ${DOCKER_VOLUMES}/postgres-gift-db:/data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: guest@guest.com
      PGADMIN_DEFAULT_PASSWORD: guest
    volumes:
      - ${DOCKER_VOLUMES}/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
